name: Check Filename Changes

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-filename-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","
          # Optionally, restrict to certain directories or file types:
          # files: |
          #   src/**
          #   docs/*.md

      - name: Check for filename changes
        id: check_names
        run: |
          #!/bin/bash
          set -e
          TARGET_FILES="test.dita file_2.txt"
          CHANGED_FILES="${{ steps.files.outputs.all_changed_files }}"
          HAS_NAME_CHANGE=0

          for pattern in $TARGET_FILES; do
            for file in $(echo $CHANGED_FILES | tr "," "\n"); do
              # Check for file name change (renamed files)
              if git diff --name-status origin/${{ github.event.pull_request.base.ref }}...HEAD | grep '^R' | grep "$pattern"; then
                HAS_NAME_CHANGE=1
                echo "Detected filename change in $file"
              fi
            done
          done

          if [[ "$HAS_NAME_CHANGE" == "1" ]]; then
            echo "Filename change detected in protected files. Failing check."
            exit 1
          else
            echo "No filename change detected in protected files."
          fi
