name: Check for Protected Filename Changes

on:
  pull_request:
    branches:
      - main

jobs:
  check-filenames:  # This is the job ID
    name: Check DITA Filename Changes  # This is the name that will appear in the UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for protected filename changes
        run: |
          PROTECTED_FILES=("file_1_rename.txt" "file_3_rename.txt")
          FILES_CHANGED=$(git diff --name-only origin/main...HEAD)
          
          echo "Checking for filename changes..."
          
          for file in "${PROTECTED_FILES[@]}"; do
            if echo "$FILES_CHANGED" | grep -q "$file"; then
              if [ -f "$file" ]; then
                echo "File $file exists, no change in filename."
              else
                echo "::error::Error: The filename '$file' has been changed or deleted. Merging is restricted. Please revert the filename change."
                exit 1
              fi
            fi
          done
          
          echo "No protected filenames were changed. All good to go!"
